- hosts: nodes
  tasks:
  - yum_repository:
      name: "docker-ce"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      description: "docker repo file"
      gpgcheck: no 

  - package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present
      skip_broken: yes

  - service:
      name: "docker"
      state: started
      enabled: yes

  - package:
      name: "python3"
      state: present

  - pip:
      name: "docker"
      state: present
      executable: pip3

  - file:
      state: directory
      path: "/ansibletask1"     

  - copy:
      dest: "/ansibletask1"
      src: "/playbook/my.html"

  - docker_image:
      name: "httpd"
      pull: yes
      state: present

  - docker_container:
      name: "httpd_container"
      image: "httpd"
      state: started
      detach: true
      interactive: true
      exposed_ports:
       - "80"
      ports:
       - "1234:80"
      volumes:
       - "/ansibletask1:/usr/local/apache2/htdocs"

  - firewalld:
      port: "80/tcp"
      port: "1234/tcp"
      state: enabled
      immediate: yes
      permanent: yes
